package com.madsam.otora.core.theme

import androidx.compose.ui.graphics.Brush
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor

// ============================================================================
// Material 3 Expressive Color System - Otoge Tracker Theme
// 
// 配色方案现在由 MaterialKolor 动态生成，见 DynamicColorScheme.kt
// 默认源颜色: #7C5CBF (紫罗兰) 定义在 Theme.kt 的 OtogeDefaultSourceColor
// ============================================================================

// ============================================================================
// Common utility colors (通用工具颜色)
// 这些是固定颜色，不随主题变化
// ============================================================================
val PurpleTheme = Color(0xFF674FA3)
val Black333 = Color(0xFF333333)
val White1000: Color = Color(0xFFFFFFFF)
val White800: Color = Color(0xFFE0E0E0)
val BlackAlpha80: Color = Color(0xAA000000)
val Yellow1000: Color = Color(0xFFFFCC22)
val Transparent: Color = Color(0x00000000)

// ============================================================================
// osu! 专用颜色
// ============================================================================
val OSU_BRIGHT_RED: Color = Color(0xFFDE4C9B)
val OSU_BRIGHT_YELLOW_HALF_TRANS: Color = Color(0x80FFCC22)

// osu! 新版等级颜色 (Tier Gradients)
val TIER_IRON_1: Color = Color(0xFFBAB3AB)
val TIER_IRON_2: Color = Color(0xFFBAB3AB)
val TIER_BRONZE_1: Color = Color(0xFFB88F7A)
val TIER_BRONZE_2: Color = Color(0xFF855C47)
val TIER_SILVER_1: Color = Color(0xFFE0E0EB)
val TIER_SILVER_2: Color = Color(0xFFA3A3C2)
val TIER_GOLD_1: Color = Color(0xFFF0E4A8)
val TIER_GOLD_2: Color = Color(0xFFE0C952)
val TIER_PLATINUM_1: Color = Color(0xFFFFFEB3) // Changed to Yellowish (was Cyan)
val TIER_PLATINUM_2: Color = Color(0xFFD4D490) // Changed to Yellowish (was Cyan)
val TIER_RHODIUM_1: Color = Color(0xFFD9F8D3)
val TIER_RHODIUM_2: Color = Color(0xFFA0CF96)
val TIER_RADIANT_1: Color = Color(0xFF97DCFF)
val TIER_RADIANT_2: Color = Color(0xFFED82FF)
val TIER_LUSTROUS_1: Color = Color(0xFFFFE600)
val TIER_LUSTROUS_2: Color = Color(0xFFED82FF)

// osu! 新版等级颜色 (Dark Mode / 深色变体)
val TIER_IRON_DARK_1: Color = Color(0xFF757575)
val TIER_IRON_DARK_2: Color = Color(0xFF616161)
val TIER_BRONZE_DARK_1: Color = Color(0xFF5D4037)
val TIER_BRONZE_DARK_2: Color = Color(0xFF3E2723)
val TIER_SILVER_DARK_1: Color = Color(0xFF616161)
val TIER_SILVER_DARK_2: Color = Color(0xFF424242)
val TIER_GOLD_DARK_1: Color = Color(0xFFF57F17)
val TIER_GOLD_DARK_2: Color = Color(0xFFFF6F00)
val TIER_PLATINUM_DARK_1: Color = Color(0xFFFBC02D) // Changed to Yellowish (was Cyan)
val TIER_PLATINUM_DARK_2: Color = Color(0xFFF9A825) // Changed to Yellowish (was Cyan)
val TIER_RHODIUM_DARK_1: Color = Color(0xFF2E7D32)
val TIER_RHODIUM_DARK_2: Color = Color(0xFF558B2F)
val TIER_RADIANT_DARK_1: Color = Color(0xFF0091EA)
val TIER_RADIANT_DARK_2: Color = Color(0xFFAA00FF)
val TIER_LUSTROUS_DARK_1: Color = Color(0xFFFFD600)
val TIER_LUSTROUS_DARK_2: Color = Color(0xFFC51162)

// osu! 旧版等级颜色 (保留用于兼容或Light Mode参考)
val OSU_LEVEL_GOLD_1: Color = Color(0xFFF5FB62)
val OSU_LEVEL_PLATINUM_1: Color = Color(0xFFFFFEB3)

// osu! 图标颜色
val OSU_ROTATE_GREEN: Color = Color(0xFF66FF73)
val OSU_HEART_RED: Color = Color(0xFFFF66AB)
val OSU_ARROW_YELLOW: Color = Color(0xFFFFD966)

// osu! 社交平台颜色
val OSU_X_BG: Color = Color(0xFF000000)
val OSU_DISCORD_BG: Color = Color(0xFF5865F2)
val OSU_DISCORD_TEXT: Color = Color(0xFFFFFFFF)

// ============================================================================
// 通用 UI 颜色
// ============================================================================
val TEXT_GRAY: Color = Color(0xFF818181)
val BG_DARK_GRAY: Color = Color(0xFF2A2A2A)

// 排名颜色
val RANKING_RED: Color = Color(0xFFD32F2F)
val RANKING_BLUE: Color = Color(0xFF2A518D)
val RANKING_GREEN: Color = Color(0xFF388E3C)
val RANKING_YELLOW: Color = Color(0xFFFBC02D)

// ============================================================================
// Chunithm 专用颜色
// ============================================================================
val CHUNI_DIFF_BASIC: Color = Color(0xFF4CAF50)
val CHUNI_DIFF_ADVANCED: Color = Color(0xFFFF9800)
val CHUNI_DIFF_EXPERT: Color = Color(0xFFE35454)
val CHUNI_DIFF_MASTER: Color = Color(0xFFBF6AFF)
val CHUNI_DIFF_ULTIMA_1: Color = Color(0xFF202020)
val CHUNI_DIFF_ULTIMA_2: Color = Color(0xFFFF3A3A)

// ============================================================================
// 渐变色 Brush
// ============================================================================
// ============================================================================
// Modern Tier Gradients (Generated by Material 3 Color System)
// ============================================================================

// Seeds
private val SeedSilver = Color(0xFFB0C4DE)   // Cool Silver (Blue-tinted for readability)
private val SeedGold = Color(0xFFFFCD00)     // Vivid Amber Gold (Orange-tinted)
private val SeedPlatinum = Color(0xFFF5DD1D) // Platinum (Between Gold and Yellow)
private val SeedBronze = Color(0xFFCD7F32)   // Bronze
private val SeedRed = Color(0xFFF44336)      // Red
private val SeedBlue = Color(0xFF2196F3)     // Blue
private val SeedGreen = Color(0xFF4CAF50)    // Green
private val SeedYellow = Color(0xFFFFEB3B)   // Yellow
private val SeedPurple = Color(0xFF9C27B0)   // Purple

// Generated Schemes (Fidelity style to preserve the metal hue)
private val SchemeSilverLight = DynamicColorScheme.generateColorScheme(SeedSilver, false, style = DynamicColorScheme.Style.FIDELITY)
private val SchemeSilverDark = DynamicColorScheme.generateColorScheme(SeedSilver, true, style = DynamicColorScheme.Style.FIDELITY)

private val SchemeGoldLight = DynamicColorScheme.generateColorScheme(SeedGold, false, style = DynamicColorScheme.Style.FIDELITY)
private val SchemeGoldDark = DynamicColorScheme.generateColorScheme(SeedGold, true, style = DynamicColorScheme.Style.FIDELITY)

private val SchemePlatinumLight = DynamicColorScheme.generateColorScheme(SeedPlatinum, false, style = DynamicColorScheme.Style.FIDELITY)
private val SchemePlatinumDark = DynamicColorScheme.generateColorScheme(SeedPlatinum, true, style = DynamicColorScheme.Style.FIDELITY)

private val SchemeBronzeLight = DynamicColorScheme.generateColorScheme(SeedBronze, false, style = DynamicColorScheme.Style.FIDELITY)
private val SchemeBronzeDark = DynamicColorScheme.generateColorScheme(SeedBronze, true, style = DynamicColorScheme.Style.FIDELITY)

private val SchemeRedLight = DynamicColorScheme.generateColorScheme(SeedRed, false, style = DynamicColorScheme.Style.FIDELITY)
private val SchemeRedDark = DynamicColorScheme.generateColorScheme(SeedRed, true, style = DynamicColorScheme.Style.FIDELITY)

private val SchemeBlueLight = DynamicColorScheme.generateColorScheme(SeedBlue, false, style = DynamicColorScheme.Style.FIDELITY)
private val SchemeBlueDark = DynamicColorScheme.generateColorScheme(SeedBlue, true, style = DynamicColorScheme.Style.FIDELITY)

private val SchemeGreenLight = DynamicColorScheme.generateColorScheme(SeedGreen, false, style = DynamicColorScheme.Style.FIDELITY)
private val SchemeGreenDark = DynamicColorScheme.generateColorScheme(SeedGreen, true, style = DynamicColorScheme.Style.FIDELITY)

private val SchemeYellowLight = DynamicColorScheme.generateColorScheme(SeedYellow, false, style = DynamicColorScheme.Style.FIDELITY)
private val SchemeYellowDark = DynamicColorScheme.generateColorScheme(SeedYellow, true, style = DynamicColorScheme.Style.FIDELITY)

private val SchemePurpleLight = DynamicColorScheme.generateColorScheme(SeedPurple, false, style = DynamicColorScheme.Style.FIDELITY)
private val SchemePurpleDark = DynamicColorScheme.generateColorScheme(SeedPurple, true, style = DynamicColorScheme.Style.FIDELITY)

private fun schemeToGradient(scheme: androidx.compose.material3.ColorScheme): Brush {
    return SolidColor(scheme.primaryContainer)
}

private fun schemeToGradientDark(scheme: androidx.compose.material3.ColorScheme): Brush {
    return SolidColor(scheme.primaryContainer)
}

private fun schemeToTextGradient(scheme: androidx.compose.material3.ColorScheme): Brush {
    return SolidColor(scheme.primaryContainer)
}

private fun schemeToTextGradientDark(scheme: androidx.compose.material3.ColorScheme): Brush {
    return SolidColor(scheme.primaryContainer)
}

object GradientBrush {
    // White / Default (Using Neutral variant)
    private val SchemeWhiteLight = DynamicColorScheme.generateColorScheme(Color(0xFFE0E0E0), false, style = DynamicColorScheme.Style.FIDELITY)
    private val SchemeWhiteDark = DynamicColorScheme.generateColorScheme(Color(0xFFE0E0E0), true, style = DynamicColorScheme.Style.FIDELITY)
    
    val TierWhiteGradient: Brush = schemeToGradient(SchemeWhiteLight)
    val TierWhiteGradientDark: Brush = schemeToGradientDark(SchemeWhiteDark)
    val TierWhiteTextGradient: Brush = schemeToTextGradient(SchemeWhiteLight)
    val TierWhiteTextGradientDark: Brush = schemeToTextGradientDark(SchemeWhiteDark)

    // Silver
    val TierSilverGradient: Brush = schemeToGradient(SchemeSilverLight)
    val TierSilverGradientDark: Brush = schemeToGradientDark(SchemeSilverDark)
    val TierSilverTextGradient: Brush = schemeToTextGradient(SchemeSilverLight)
    val TierSilverTextGradientDark: Brush = schemeToTextGradientDark(SchemeSilverDark)

    // Gold
    val TierGoldGradient: Brush = schemeToGradient(SchemeGoldLight)
    val TierGoldGradientDark: Brush = schemeToGradientDark(SchemeGoldDark)
    val TierGoldTextGradient: Brush = schemeToTextGradient(SchemeGoldLight)
    val TierGoldTextGradientDark: Brush = schemeToTextGradientDark(SchemeGoldDark)

    // Platinum
    val TierPlatinumGradient: Brush = schemeToGradient(SchemePlatinumLight)
    val TierPlatinumGradientDark: Brush = schemeToGradientDark(SchemePlatinumDark)
    val TierPlatinumTextGradient: Brush = Brush.verticalGradient(
        0.0f to SchemeGoldLight.primaryContainer,
        0.5f to SchemePlatinumLight.primaryContainer,
        1.0f to SchemeGoldLight.primaryContainer
    )
    val TierPlatinumTextGradientDark: Brush = Brush.verticalGradient(
        0.0f to SchemeGoldDark.primaryContainer,
        0.5f to SchemePlatinumDark.primaryContainer,
        1.0f to SchemeGoldDark.primaryContainer
    )

    // Bronze
    val TierBronzeGradient: Brush = schemeToGradient(SchemeBronzeLight)
    val TierBronzeGradientDark: Brush = schemeToGradientDark(SchemeBronzeDark)
    val TierBronzeTextGradient: Brush = schemeToTextGradient(SchemeBronzeLight)
    val TierBronzeTextGradientDark: Brush = schemeToTextGradientDark(SchemeBronzeDark)

    // Red
    val TierRedGradient: Brush = schemeToGradient(SchemeRedLight)
    val TierRedGradientDark: Brush = schemeToGradientDark(SchemeRedDark)
    val TierRedTextGradient: Brush = schemeToTextGradient(SchemeRedLight)
    val TierRedTextGradientDark: Brush = schemeToTextGradientDark(SchemeRedDark)

    // Blue
    val TierBlueGradient: Brush = schemeToGradient(SchemeBlueLight)
    val TierBlueGradientDark: Brush = schemeToGradientDark(SchemeBlueDark)
    val TierBlueTextGradient: Brush = schemeToTextGradient(SchemeBlueLight)
    val TierBlueTextGradientDark: Brush = schemeToTextGradientDark(SchemeBlueDark)

    // Green
    val TierGreenGradient: Brush = schemeToGradient(SchemeGreenLight)
    val TierGreenGradientDark: Brush = schemeToGradientDark(SchemeGreenDark)
    val TierGreenTextGradient: Brush = schemeToTextGradient(SchemeGreenLight)
    val TierGreenTextGradientDark: Brush = schemeToTextGradientDark(SchemeGreenDark)

    // Yellow
    val TierYellowGradient: Brush = schemeToGradient(SchemeYellowLight)
    val TierYellowGradientDark: Brush = schemeToGradientDark(SchemeYellowDark)
    val TierYellowTextGradient: Brush = schemeToTextGradient(SchemeYellowLight)
    val TierYellowTextGradientDark: Brush = schemeToTextGradientDark(SchemeYellowDark)

    // Purple
    val TierPurpleGradient: Brush = schemeToGradient(SchemePurpleLight)
    val TierPurpleGradientDark: Brush = schemeToGradientDark(SchemePurpleDark)
    val TierPurpleTextGradient: Brush = schemeToTextGradient(SchemePurpleLight)
    val TierPurpleTextGradientDark: Brush = schemeToTextGradientDark(SchemePurpleDark)

    // Rainbow
    val TierRainbowGradient: Brush = Brush.verticalGradient(
        0.0f to SchemeBlueLight.primaryContainer,
        0.25f to SchemePurpleLight.primaryContainer,
        0.5f to SchemeRedLight.primaryContainer,
        0.75f to SchemeGoldLight.primaryContainer,
        1.0f to SchemeGreenLight.primaryContainer
    )
    val TierRainbowGradientDark: Brush = Brush.verticalGradient(
        0.0f to SchemeBlueDark.primaryContainer,
        0.25f to SchemePurpleDark.primaryContainer,
        0.5f to SchemeRedDark.primaryContainer,
        0.75f to SchemeGoldDark.primaryContainer,
        1.0f to SchemeGreenDark.primaryContainer
    )

    val TierRainbowTextGradient: Brush = Brush.verticalGradient(
        0.2f to SchemeBlueLight.primaryContainer,
        0.4f to SchemePurpleLight.primaryContainer,
        0.5f to SchemeRedLight.primaryContainer,
        0.6f to SchemeGoldLight.primaryContainer,
        0.8f to SchemeGreenLight.primaryContainer
    )
    val TierRainbowTextGradientDark: Brush = Brush.verticalGradient(
        0.2f to SchemeBlueDark.primaryContainer,
        0.4f to SchemePurpleDark.primaryContainer,
        0.5f to SchemeRedDark.primaryContainer,
        0.6f to SchemeGoldDark.primaryContainer,
        0.8f to SchemeGreenDark.primaryContainer
    )

    // Rainbow Max
    val TierRainbowMaxGradient: Brush = Brush.verticalGradient(
        0.0f to SchemeGoldLight.primaryContainer,
        0.25f to SchemeRedLight.primaryContainer,
        0.5f to SchemeBlueLight.primaryContainer,
        0.75f to SchemeGreenLight.primaryContainer,
        1.0f to SchemePurpleLight.primaryContainer
    )
    val TierRainbowMaxGradientDark: Brush = Brush.verticalGradient(
        0.0f to SchemeGoldDark.primaryContainer,
        0.25f to SchemeRedDark.primaryContainer,
        0.5f to SchemeBlueDark.primaryContainer,
        0.75f to SchemeGreenDark.primaryContainer,
        1.0f to SchemePurpleDark.primaryContainer
    )

    val TierRainbowMaxTextGradient: Brush = Brush.verticalGradient(
        0.2f to SchemeGoldLight.primaryContainer,
        0.4f to SchemeRedLight.primaryContainer,
        0.5f to SchemeBlueLight.primaryContainer,
        0.6f to SchemeGreenLight.primaryContainer,
        0.8f to SchemePurpleLight.primaryContainer
    )
    val TierRainbowMaxTextGradientDark: Brush = Brush.verticalGradient(
        0.2f to SchemeGoldDark.primaryContainer,
        0.4f to SchemeRedDark.primaryContainer,
        0.5f to SchemeBlueDark.primaryContainer,
        0.6f to SchemeGreenDark.primaryContainer,
        0.8f to SchemePurpleDark.primaryContainer
    )
}

object TierColors {
    val GoldContainerLight = SchemeGoldLight.primaryContainer
}
